<?php

use Illuminate\Database\Seeder;

class TeamsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('teams')->delete();
        
        \DB::table('teams')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'AFC Bournemouth',
                'matches_played' => 8,
                'win' => 5,
                'lose' => 2,
                'draw' => 1,
                'goal_difference' => 4,
                'points' => 16,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Arsenal FC',
                'matches_played' => 8,
                'win' => 6,
                'lose' => 2,
                'draw' => 0,
                'goal_difference' => 9,
                'points' => 18,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Brighton & Hove Albion',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 4,
                'draw' => 2,
                'goal_difference' => -4,
                'points' => 8,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'Chelsea FC',
                'matches_played' => 8,
                'win' => 6,
                'lose' => 0,
                'draw' => 2,
                'goal_difference' => 13,
                'points' => 20,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'Crystal Palace',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 5,
                'draw' => 1,
                'goal_difference' => -4,
                'points' => 7,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'Everton FC',
                'matches_played' => 8,
                'win' => 3,
                'lose' => 2,
                'draw' => 3,
                'goal_difference' => 1,
                'points' => 12,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Huddersfield Town',
                'matches_played' => 8,
                'win' => 0,
                'lose' => 5,
                'draw' => 3,
                'goal_difference' => -13,
                'points' => 3,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Leicester City',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 4,
                'draw' => 0,
                'goal_difference' => 2,
                'points' => 12,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'Liverpool FC',
                'matches_played' => 8,
                'win' => 6,
                'lose' => 0,
                'draw' => 2,
                'goal_difference' => 12,
                'points' => 20,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'Manchester City',
                'matches_played' => 8,
                'win' => 6,
                'lose' => 0,
                'draw' => 2,
                'goal_difference' => 18,
                'points' => 20,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'Manchester United',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 3,
                'draw' => 1,
                'goal_difference' => -1,
                'points' => 13,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'Newcastle United',
                'matches_played' => 8,
                'win' => 0,
                'lose' => 6,
                'draw' => 2,
                'goal_difference' => -7,
                'points' => 2,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'Southampton FC',
                'matches_played' => 8,
                'win' => 1,
                'lose' => 5,
                'draw' => 2,
                'goal_difference' => -8,
                'points' => 5,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'Tottenham Hotspur',
                'matches_played' => 8,
                'win' => 6,
                'lose' => 2,
                'draw' => 0,
                'goal_difference' => 8,
                'points' => 18,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'Watford FC',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 3,
                'draw' => 1,
                'goal_difference' => -1,
                'points' => 13,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'West Ham United',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 5,
                'draw' => 1,
                'goal_difference' => -5,
                'points' => 7,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'Wolverhampton Wanderers',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 1,
                'draw' => 3,
                'goal_difference' => 3,
                'points' => 15,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'Cardiff City',
                'matches_played' => 8,
                'win' => 0,
                'lose' => 6,
                'draw' => 2,
                'goal_difference' => -13,
                'points' => 2,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'Fullham',
                'matches_played' => 8,
                'win' => 1,
                'lose' => 5,
                'draw' => 2,
                'goal_difference' => -11,
                'points' => 5,
                'league_id' => 1,
                'created_at' => '2018-10-09 22:02:40',
                'updated_at' => '2018-10-09 22:02:40',
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'AC Milan',
                'matches_played' => 7,
                'win' => 3,
                'lose' => 1,
                'draw' => 3,
                'goal_difference' => 5,
                'points' => 12,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'ACF Fiorentina',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 3,
                'draw' => 1,
                'goal_difference' => 8,
                'points' => 13,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'AS Roma',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 2,
                'draw' => 2,
                'goal_difference' => 6,
                'points' => 14,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'Atalanta',
                'matches_played' => 8,
                'win' => 1,
                'lose' => 4,
                'draw' => 3,
                'goal_difference' => -2,
                'points' => 6,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'Bologna FC',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 5,
                'draw' => 1,
                'goal_difference' => -6,
                'points' => 7,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'Cagliari Calcio',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 3,
                'draw' => 3,
                'goal_difference' => -3,
                'points' => 9,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'Chievo Verona',
                'matches_played' => 8,
                'win' => 0,
                'lose' => 2,
                'draw' => 6,
                'goal_difference' => -1,
                'points' => -13,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'Empoli FC',
                'matches_played' => 8,
                'win' => 1,
                'lose' => 5,
                'draw' => 2,
                'goal_difference' => -5,
                'points' => 5,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'Frosinone Calcio',
                'matches_played' => 8,
                'win' => 0,
                'lose' => 7,
                'draw' => 1,
                'goal_difference' => -18,
                'points' => 1,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'Genoa CFC',
                'matches_played' => 7,
                'win' => 4,
                'lose' => 3,
                'draw' => 0,
                'goal_difference' => -2,
                'points' => 12,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'Inter',
                'matches_played' => 8,
                'win' => 5,
                'lose' => 2,
                'draw' => 1,
                'goal_difference' => 6,
                'points' => 16,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'Juventus',
                'matches_played' => 8,
                'win' => 8,
                'lose' => 0,
                'draw' => 0,
                'goal_difference' => 13,
                'points' => 24,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'Lazio Roma',
                'matches_played' => 8,
                'win' => 5,
                'lose' => 3,
                'draw' => 0,
                'goal_difference' => 2,
                'points' => 15,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'Parma Calcio 1913',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 3,
                'draw' => 1,
                'goal_difference' => 0,
                'points' => 13,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'Sampdoria',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 2,
                'draw' => 2,
                'goal_difference' => 8,
                'points' => 14,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'Sassuolo Calcio',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 3,
                'draw' => 1,
                'goal_difference' => 1,
                'points' => 13,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'SPAL 2013 Ferrara',
                'matches_played' => 8,
                'win' => 3,
                'lose' => 5,
                'draw' => 0,
                'goal_difference' => -4,
                'points' => 9,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'SSC Napoli',
                'matches_played' => 8,
                'win' => 6,
                'lose' => 2,
                'draw' => 0,
                'goal_difference' => 5,
                'points' => 18,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'Torino FC',
                'matches_played' => 8,
                'win' => 3,
                'lose' => 2,
                'draw' => 3,
                'goal_difference' => 0,
                'points' => 12,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'Udinese Calcio',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 4,
                'draw' => 2,
                'goal_difference' => -2,
                'points' => 8,
                'league_id' => 2,
                'created_at' => '2018-10-10 13:31:44',
                'updated_at' => '2018-10-10 13:31:44',
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'Alaves',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 2,
                'draw' => 2,
                'goal_difference' => 3,
                'points' => 14,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'Ath Bilbao',
                'matches_played' => 7,
                'win' => 1,
                'lose' => 2,
                'draw' => 4,
                'goal_difference' => -4,
                'points' => 7,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'Atl.Madrid',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 1,
                'draw' => 3,
                'goal_difference' => 5,
                'points' => 15,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'Barcelona',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 1,
                'draw' => 3,
                'goal_difference' => 10,
                'points' => 15,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'Betis',
                'matches_played' => 8,
                'win' => 3,
                'lose' => 2,
                'draw' => 3,
                'goal_difference' => -1,
                'points' => 12,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'Celta Vigo',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 2,
                'draw' => 4,
                'goal_difference' => 1,
                'points' => 10,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'Eibar',
                'matches_played' => 8,
                'win' => 3,
                'lose' => 4,
                'draw' => 1,
                'goal_difference' => -3,
                'points' => 10,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'Espanyol',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 2,
                'draw' => 2,
                'goal_difference' => 4,
                'points' => 14,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'Getafe',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 3,
                'draw' => 3,
                'goal_difference' => -1,
                'points' => 9,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'Girona',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 3,
                'draw' => 3,
                'goal_difference' => -3,
                'points' => 9,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'Huesca',
                'matches_played' => 8,
                'win' => 1,
                'lose' => 5,
                'draw' => 2,
                'goal_difference' => -11,
                'points' => 5,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'Leganes',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 5,
                'draw' => 1,
                'goal_difference' => -5,
                'points' => 7,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            51 => 
            array (
                'id' => 53,
                'name' => 'Levante',
                'matches_played' => 8,
                'win' => 3,
                'lose' => 4,
                'draw' => 1,
                'goal_difference' => -2,
                'points' => 10,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            52 => 
            array (
                'id' => 54,
                'name' => 'Rayo Vallecano',
                'matches_played' => 7,
                'win' => 1,
                'lose' => 4,
                'draw' => 2,
                'goal_difference' => -8,
                'points' => 5,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            53 => 
            array (
                'id' => 55,
                'name' => 'Real Madrid',
                'matches_played' => 8,
                'win' => 4,
                'lose' => 2,
                'draw' => 2,
                'goal_difference' => 5,
                'points' => 14,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            54 => 
            array (
                'id' => 56,
                'name' => 'Real Sociedad',
                'matches_played' => 8,
                'win' => 3,
                'lose' => 3,
                'draw' => 2,
                'goal_difference' => 1,
                'points' => 11,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            55 => 
            array (
                'id' => 57,
                'name' => 'Sevilla FC',
                'matches_played' => 8,
                'win' => 5,
                'lose' => 2,
                'draw' => 1,
                'goal_difference' => 10,
                'points' => 16,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            56 => 
            array (
                'id' => 58,
                'name' => 'Valencia',
                'matches_played' => 8,
                'win' => 1,
                'lose' => 1,
                'draw' => 6,
                'goal_difference' => -1,
                'points' => 9,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            57 => 
            array (
                'id' => 59,
                'name' => 'Real Valladolid',
                'matches_played' => 8,
                'win' => 3,
                'lose' => 2,
                'draw' => 3,
                'goal_difference' => 1,
                'points' => 12,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            58 => 
            array (
                'id' => 60,
                'name' => 'Villarreal',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 4,
                'draw' => 2,
                'goal_difference' => -1,
                'points' => 8,
                'league_id' => 4,
                'created_at' => '2018-10-10 13:46:34',
                'updated_at' => '2018-10-10 13:46:34',
            ),
            59 => 
            array (
                'id' => 61,
                'name' => 'Nürnberg',
                'matches_played' => 7,
                'win' => 2,
                'lose' => 3,
                'draw' => 2,
                'goal_difference' => 9,
                'points' => 8,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            60 => 
            array (
                'id' => 62,
                'name' => 'Mainz',
                'matches_played' => 7,
                'win' => 2,
                'lose' => 2,
                'draw' => 3,
                'goal_difference' => 0,
                'points' => 9,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            61 => 
            array (
                'id' => 63,
                'name' => 'Hoffenheim',
                'matches_played' => 7,
                'win' => 2,
                'lose' => 4,
                'draw' => 1,
                'goal_difference' => -1,
                'points' => 7,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            62 => 
            array (
                'id' => 64,
                'name' => 'Bayer Leverkusen',
                'matches_played' => 7,
                'win' => 2,
                'lose' => 4,
                'draw' => 1,
                'goal_difference' => -6,
                'points' => 7,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            63 => 
            array (
                'id' => 65,
                'name' => 'Borussia Monchengladbach',
                'matches_played' => 7,
                'win' => 4,
                'lose' => 1,
                'draw' => 2,
                'goal_difference' => 6,
                'points' => 14,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            64 => 
            array (
                'id' => 66,
                'name' => 'Borussia Dortmund',
                'matches_played' => 7,
                'win' => 5,
                'lose' => 0,
                'draw' => 2,
                'goal_difference' => 15,
                'points' => 17,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            65 => 
            array (
                'id' => 67,
                'name' => 'Eintracht Frankfurt',
                'matches_played' => 7,
                'win' => 3,
                'lose' => 3,
                'draw' => 1,
                'goal_difference' => 1,
                'points' => 10,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            66 => 
            array (
                'id' => 68,
                'name' => 'FC Augsburg',
                'matches_played' => 7,
                'win' => 2,
                'lose' => 3,
                'draw' => 2,
                'goal_difference' => 1,
                'points' => 8,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            67 => 
            array (
                'id' => 69,
                'name' => 'Schalke 04',
                'matches_played' => 7,
                'win' => 2,
                'lose' => 5,
                'draw' => 0,
                'goal_difference' => -4,
                'points' => 6,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            68 => 
            array (
                'id' => 70,
                'name' => 'Fortuna Düsseldorf',
                'matches_played' => 7,
                'win' => 1,
                'lose' => 4,
                'draw' => 2,
                'goal_difference' => -6,
                'points' => 5,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            69 => 
            array (
                'id' => 71,
                'name' => 'Hannover 96',
                'matches_played' => 7,
                'win' => 1,
                'lose' => 4,
                'draw' => 2,
                'goal_difference' => 6,
                'points' => 5,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            70 => 
            array (
                'id' => 72,
                'name' => 'Hertha Berlin',
                'matches_played' => 7,
                'win' => 4,
                'lose' => 1,
                'draw' => 2,
                'goal_difference' => 5,
                'points' => 14,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            71 => 
            array (
                'id' => 73,
                'name' => 'RB Leipzig',
                'matches_played' => 7,
                'win' => 4,
                'lose' => 1,
                'draw' => 2,
                'goal_difference' => 5,
                'points' => 14,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            72 => 
            array (
                'id' => 74,
                'name' => 'SC Freiburg',
                'matches_played' => 7,
                'win' => 2,
                'lose' => 3,
                'draw' => 2,
                'goal_difference' => 4,
                'points' => 8,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            73 => 
            array (
                'id' => 75,
                'name' => 'VfB Stuttgart',
                'matches_played' => 7,
                'win' => 1,
                'lose' => 4,
                'draw' => 2,
                'goal_difference' => -7,
                'points' => 5,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            74 => 
            array (
                'id' => 76,
                'name' => 'VfL Wolfsburg',
                'matches_played' => 7,
                'win' => 2,
                'lose' => 3,
                'draw' => 2,
                'goal_difference' => -1,
                'points' => 9,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            75 => 
            array (
                'id' => 77,
                'name' => 'Werder Bremen',
                'matches_played' => 7,
                'win' => 4,
                'lose' => 1,
                'draw' => 2,
                'goal_difference' => 5,
                'points' => 14,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            76 => 
            array (
                'id' => 78,
                'name' => 'Bayern Munich',
                'matches_played' => 7,
                'win' => 4,
                'lose' => 2,
                'draw' => 1,
                'goal_difference' => 4,
                'points' => 13,
                'league_id' => 3,
                'created_at' => '2018-10-10 14:00:50',
                'updated_at' => '2018-10-10 14:00:50',
            ),
            77 => 
            array (
                'id' => 81,
                'name' => 'update',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 2,
                'draw' => 2,
                'goal_difference' => 2,
                'points' => 2,
                'league_id' => 4,
                'created_at' => '2018-10-10 22:51:26',
                'updated_at' => '2018-10-10 23:30:06',
            ),
            78 => 
            array (
                'id' => 82,
                'name' => 'Burnley',
                'matches_played' => 8,
                'win' => 2,
                'lose' => 4,
                'draw' => 2,
                'goal_difference' => -2,
                'points' => 8,
                'league_id' => 1,
                'created_at' => '2018-10-11 18:06:15',
                'updated_at' => '2018-10-11 18:06:15',
            ),
        ));
        
        
    }
}